#!/usr/bin/env python2
from __future__ import print_function
import os
import sys
import time
import threading
import argparse
from telemetric import TMClient

###############################################################################
# Main
###############################################################################

# Set up argument parsing
parser = argparse.ArgumentParser(description="")

parser.add_argument("--ip-address",
                    required=True,
                    type=str)

parser.add_argument("--port",
                    required=True,
                    type=int)

parser.add_argument("--protos",
                    required=False,
                    type=str,
                    nargs = '*',
                    default=[],
                    help = "List of .proto files to be received in messages")

parser.add_argument("--print-all",
                    required=False,
                    action='store_true',
                    help = "Display data for all items instead of just the first")

parser.add_argument("--brief",
                    required=False,
                    action='store_true',
                    help = "Only display message headers, no data")

parser.add_argument("--json-dump",
                    required=False,
                    action='store_true',
                    help = "Dump JSON messages instead of pretty-printing")

# Parse all arguments and bind to the specified IP address and port
args = parser.parse_args(sys.argv[1:])
client = TMClient(args.ip_address, args.port,
                  protos=args.protos,
                  json_dump=args.json_dump,
                  print_all=args.print_all)
client.run()
